ekf_local:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: false

    # Your TF chain is odom -> base_footprint -> base_link
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    # Wheel odometry owns the odom -> base_footprint TF; EKF only provides filtered odometry topic
    publish_tf: false

    # Fuse your wheel odom
    odom0: /smart_car/wheel/odom
    odom0_config: [false, false, false,
                   false, false, true,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 10
    odom0_nodelay: false
    odom0_differential: false
    odom0_relative: false

    # IMU from Gazebo
    imu0: /imu_data
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  false, false, false]
    imu0_nodelay: false
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true

    print_diagnostics: true
    reset_on_time_jump: true
